### ISSUE TITLE
fabric.js로 도형(사각형, 원) 구현하기

### ISSUE THREAD

**Issue by Bumang-Cyber** [LaughLog/laugh-log#31]
## Description

fabric.js로 사각형, 원 구현하기

## Todo

- [ ] 도형 박스 선택할 수 있게 하기
- [ ] fabric.js로 사각형, 원 구현하기
- [ ] 이동 가능하게 하기
