### ISSUE TITLE
음성채팅 구현

### ISSUE THREAD

**Issue by ovoxiix** [LaughLog/laugh-log#41]
## Description
화이트보드에 음성채팅을 구현할 예정입니다.

## Todo
- [ ] 시그널링 서버 구현
- [ ] peer-to-peer 음성 연결 구현
- [ ] STUN 서버 추가
