### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by JitHoon** [LaughLog/laugh-log#65]
## Todo (기능)

- [ ] 초기 로딩속도 개선
- [ ] 로그인 후 보드 이동 버튼 및 홈 버튼 추가
- [ ] 미들웨어 설정
- [ ] 초기 양식 세팅 (디자인 개선)
- [ ] 이미지 등록
- [ ] 드래그 & 드롭

## Todo (포폴)

- [ ] 배포 (네트워크 내용 정리)
- [ ] node.js express
- [ ] 소켓
- [ ] 서버 과부하 개선
- [ ] 렌더링 최적화 개선
